-- =============================================================================
-- DEMO BOOKS FOR KITAAB KHARIDO
-- Run this in Supabase SQL Editor AFTER running supabase-schema.sql
-- This adds 45 additional demo books across all categories
-- =============================================================================

-- Clear existing books first (optional — remove if you want to keep the 8 seed books)
-- TRUNCATE public.books CASCADE;

INSERT INTO public.books (
  title, author, category, sub_category, price, original_price, discount_tag,
  condition, stock_quantity, image_urls, isbn, publisher, edition, language,
  description, active, featured
) VALUES

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — JEE Preparation
-- ═══════════════════════════════════════════════════════════════════
(
  'HC Verma - Concepts of Physics Vol 2',
  'HC Verma',
  'Academic',
  'Physics/JEE',
  180.00,
  450.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=HC+Verma+Vol+2'],
  '978-8177091878',
  'Bharati Bhawan Publishers',
  '2022 Edition',
  'English',
  'Second volume covering electromagnetism, optics, thermodynamics, and modern physics. Essential for JEE Main & Advanced with 500+ solved problems and conceptual questions.',
  true,
  true
),
(
  'Irodov - Problems in General Physics',
  'I.E. Irodov',
  'Academic',
  'Physics/JEE',
  220.00,
  550.00,
  '60% OFF',
  'Like New',
  5,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=Irodov+Physics'],
  '978-9386139281',
  'Arihant Publications',
  '2023 Edition',
  'English',
  'The holy grail for JEE Advanced physics. Contains 1800+ challenging problems with detailed solutions. Recommended for students targeting top 500 ranks in JEE.',
  true,
  true
),
(
  'Cengage Physics Series (Set of 6)',
  'B.M. Sharma',
  'Academic',
  'Physics/JEE',
  650.00,
  1800.00,
  '60% OFF',
  'Good',
  3,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=Cengage+Physics'],
  NULL,
  'Cengage Learning India',
  '2023 Edition',
  'English',
  'Complete set of 6 books covering all JEE physics topics — Mechanics, Thermodynamics, Waves, Electro & Magnetism, Optics, and Modern Physics. With theory, examples, and exercises.',
  true,
  false
),
(
  'MS Chouhan - Organic Chemistry for JEE',
  'MS Chouhan',
  'Academic',
  'Chemistry/JEE',
  200.00,
  499.00,
  '60% OFF',
  'Like New',
  7,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=MS+Chouhan+Organic'],
  NULL,
  'Vikas Publishing',
  '2023 Edition',
  'English',
  'Most recommended organic chemistry book for JEE. Covers reaction mechanisms, stereochemistry, and named reactions with 3000+ practice questions sorted by difficulty level.',
  true,
  true
),
(
  'N Avasthi - Physical Chemistry',
  'N. Avasthi',
  'Academic',
  'Chemistry/JEE',
  175.00,
  450.00,
  '60% OFF',
  'Good',
  6,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=N+Avasthi+Chem'],
  NULL,
  'Shri Balaji Publications',
  '2022 Edition',
  'English',
  'Best-selling physical chemistry book for JEE preparation. Includes numerical problems, theory summaries, and previous year JEE questions chapter-wise.',
  true,
  false
),
(
  'RC Mukherjee - Modern Approach to Chemical Calculations',
  'RC Mukherjee',
  'Academic',
  'Chemistry/JEE',
  130.00,
  350.00,
  '60% OFF',
  'Fair',
  9,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=RC+Mukherjee'],
  '978-8177096415',
  'Bharati Bhawan Publishers',
  'Latest Edition',
  'English',
  'Classic book for mastering chemical calculations in physical chemistry. Covers mole concept, stoichiometry, equilibrium, and thermodynamics with graded exercises.',
  true,
  false
),
(
  'Arihant Skills in Mathematics Series (Set of 7)',
  'Various Authors',
  'Academic',
  'Mathematics/JEE',
  800.00,
  2200.00,
  '60% OFF',
  'Good',
  2,
  ARRAY['https://placehold.co/300x400/1a1a2e/3a0ca3?text=Arihant+Maths+Set'],
  NULL,
  'Arihant Publications',
  '2023 Edition',
  'English',
  'Complete set of 7 books covering Algebra, Coordinate Geometry, Calculus, Vectors & 3D, Trigonometry, Probability, and Mathematical Reasoning for JEE Main & Advanced.',
  true,
  true
),
(
  'SL Loney - Coordinate Geometry',
  'SL Loney',
  'Academic',
  'Mathematics/JEE',
  120.00,
  325.00,
  '60% OFF',
  'Fair',
  4,
  ARRAY['https://placehold.co/300x400/1a1a2e/3a0ca3?text=SL+Loney+Coord'],
  NULL,
 'Arihant Publications',
  '2022 Edition',
  'English',
  'Timeless classic for coordinate geometry. Covers straight lines, circles, parabola, ellipse, and hyperbola in depth. Essential for JEE Advanced geometry problems.',
  true,
  false
),
(
  '41 Years JEE Main Chapterwise Solutions (Physics)',
  'Arihant Experts',
  'Academic',
  'Physics/JEE',
  160.00,
  425.00,
  '60% OFF',
  'Good',
  10,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=41+Yrs+JEE+Phy'],
  NULL,
  'Arihant Publications',
  '2024 Edition',
  'English',
  'Chapter-wise collection of all JEE Main Physics questions from 1983-2024 with detailed solutions. The most authentic practice resource for JEE Main.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — NEET Preparation
-- ═══════════════════════════════════════════════════════════════════
(
  'NCERT Physics Class 11 & 12 Set',
  'NCERT',
  'Academic',
  'Physics/NEET',
  140.00,
  380.00,
  '60% OFF',
  'Good',
  12,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=NCERT+Physics+Set'],
  NULL,
  'NCERT',
  'Latest Edition',
  'English',
  'Complete NCERT Physics textbook set for Class 11 and 12. Foundation of NEET Physics preparation — covers mechanics, optics, thermodynamics, electricity, and modern physics.',
  true,
  true
),
(
  'Errorless Chemistry (Universal Self Scorer)',
  'Universal Books',
  'Academic',
  'Chemistry/NEET',
  250.00,
  650.00,
  '60% OFF',
  'Like New',
  6,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=Errorless+Chemistry'],
  NULL,
  'Universal Book Depot',
  '2023 Edition',
  'English',
  'Comprehensive chemistry book covering Physical, Organic, and Inorganic Chemistry with 12000+ MCQs for NEET. Includes previous year NEET questions with solutions.',
  true,
  true
),
(
  'GRB Organic Chemistry by OP Tandon',
  'OP Tandon',
  'Academic',
  'Chemistry/NEET',
  190.00,
  495.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=GRB+Organic'],
  NULL,
  'GRB Publications',
  '2023 Edition',
  'English',
  'Detailed organic chemistry book for NEET with reaction mechanisms, named reactions, and 5000+ practice questions. Covers all topics from NCERT plus advanced concepts.',
  true,
  false
),
(
  'MTG NEET Previous Year Papers (36 Years)',
  'MTG Editorial Board',
  'Academic',
  'NEET',
  220.00,
  580.00,
  '60% OFF',
  'Good',
  11,
  ARRAY['https://placehold.co/300x400/1a1a2e/06d6a0?text=MTG+NEET+36+Yrs'],
  NULL,
  'MTG Learning Media',
  '2024 Edition',
  'English',
  '36 years of NEET/AIPMT solved papers chapter-wise. Includes unit tests, model test papers, and detailed explanations. Most authentic NEET practice resource.',
  true,
  true
),
(
  'Trueman''s Elementary Biology (Vol 1 & 2)',
  'K.N. Bhatia',
  'Academic',
  'Biology/NEET',
  300.00,
  780.00,
  '60% OFF',
  'Like New',
  5,
  ARRAY['https://placehold.co/300x400/1a1a2e/06d6a0?text=Truemans+Biology'],
  NULL,
  'Trueemann''s',
  'Latest Edition',
  'English',
  'Two-volume set covering the entire biology syllabus for NEET. Detailed diagrams, flow charts, and MCQs. Essential companion to NCERT Biology.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — UPSC Preparation
-- ═══════════════════════════════════════════════════════════════════
(
  'Laxmikanth - Indian Polity',
  'M. Laxmikanth',
  'Academic',
  'UPSC',
  220.00,
  575.00,
  '60% OFF',
  'Like New',
  15,
  ARRAY['https://placehold.co/300x400/16213e/f59e0b?text=Laxmikanth+Polity'],
  '978-9387420994',
  'McGraw Hill Education',
  '7th Edition',
  'English',
  'The bible for UPSC Civil Services Indian Polity. Covers the entire Indian political system, Constitution, governance, and international relations. Read by every serious UPSC aspirant.',
  true,
  true
),
(
  'Spectrum - A Brief History of Modern India',
  'Spectrum Books',
  'Academic',
  'UPSC',
  170.00,
  450.00,
  '60% OFF',
  'Good',
  10,
  ARRAY['https://placehold.co/300x400/16213e/f59e0b?text=Spectrum+History'],
  '978-9387586325',
  'Spectrum Books Pvt. Ltd',
  'Latest Edition',
  'English',
  'Most recommended book for UPSC Modern Indian History. Concise yet comprehensive coverage of British India, freedom struggle, and post-independence developments.',
  true,
  true
),
(
  'Shankar IAS Environment Book',
  'Shankar IAS Academy',
  'Academic',
  'UPSC',
  160.00,
  420.00,
  '60% OFF',
  'Good',
  7,
  ARRAY['https://placehold.co/300x400/16213e/06d6a0?text=Shankar+Environment'],
  NULL,
  'Shankar IAS Academy',
  '2023 Edition',
  'English',
  'Comprehensive coverage of Environment and Ecology for UPSC Prelims and Mains. Includes biodiversity, climate change, pollution, and international conventions.',
  true,
  false
),
(
  'Oxford School Atlas',
  'Oxford University Press',
  'Academic',
  'UPSC',
  250.00,
  650.00,
  '60% OFF',
  'Like New',
  4,
  ARRAY['https://placehold.co/300x400/16213e/e94560?text=Oxford+Atlas'],
  '978-0199496619',
  'Oxford University Press',
  '35th Edition',
  'English',
  'Essential atlas for UPSC Geography preparation. Contains detailed maps of India and the world, geographical data, and thematic maps for environmental and economic topics.',
  true,
  false
),
(
  'Certificate Physical & Human Geography',
  'Goh Cheng Leong',
  'Academic',
  'UPSC',
  130.00,
  340.00,
  '60% OFF',
  'Good',
  6,
  ARRAY['https://placehold.co/300x400/16213e/f59e0b?text=Goh+Cheng+Leong'],
  '978-0195628166',
  'Oxford University Press',
  'Latest Edition',
  'English',
  'Fundamental book for UPSC Geography covering physical geography, climatology, oceanography, and human geography. Clear explanations with diagrams and illustrations.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — CAT & MBA Preparation
-- ═══════════════════════════════════════════════════════════════════
(
  'Arun Sharma - Quantitative Aptitude for CAT',
  'Arun Sharma',
  'Academic',
  'CAT/MBA',
  240.00,
  625.00,
  '60% OFF',
  'Good',
  9,
  ARRAY['https://placehold.co/300x400/1a1a2e/3a0ca3?text=Arun+Sharma+QA'],
  '978-9353946274',
  'McGraw Hill Education',
  '9th Edition',
  'English',
  'Most popular book for CAT Quantitative Aptitude. Covers number systems, algebra, geometry, and modern math with 5000+ practice questions across 5 difficulty levels.',
  true,
  true
),
(
  'How to Prepare for Verbal Ability & RC for CAT',
  'Arun Sharma & Meenakshi Upadhyay',
  'Academic',
  'CAT/MBA',
  200.00,
  550.00,
  '60% OFF',
  'Like New',
  7,
  ARRAY['https://placehold.co/300x400/1a1a2e/f59e0b?text=Verbal+Ability+CAT'],
  '978-9353946304',
  'McGraw Hill Education',
  'Latest Edition',
  'English',
  'Comprehensive verbal ability book for CAT covering reading comprehension, verbal reasoning, para jumbles, and vocabulary. Includes 200+ RC passages with detailed analysis.',
  true,
  false
),
(
  'R.S. Aggarwal - Logical Reasoning',
  'R.S. Aggarwal',
  'Academic',
  'CAT/MBA',
  150.00,
  395.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=RS+Aggarwal+LR'],
  NULL,
  'S. Chand & Co.',
  'Latest Edition',
  'English',
  'Classic book for logical reasoning covering series, blood relations, coding-decoding, puzzles, and analytical reasoning. Useful for CAT, banking, and all competitive exams.',
  true,
  false
),
(
  'Data Interpretation & Logical Reasoning for CAT',
  'Arun Sharma',
  'Academic',
  'CAT/MBA',
  210.00,
  575.00,
  '60% OFF',
  'Good',
  5,
  ARRAY['https://placehold.co/300x400/1a1a2e/06d6a0?text=DILR+CAT'],
  '978-9353946298',
  'McGraw Hill Education',
  'Latest Edition',
  'English',
  'Specialized book for CAT DILR section covering tables, graphs, puzzles, binary logic, and games & tournaments. Includes previous year CAT questions with solutions.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — GATE Preparation
-- ═══════════════════════════════════════════════════════════════════
(
  'Made Easy Engineering Mathematics',
  'Made Easy Editorial Board',
  'Academic',
  'GATE',
  280.00,
  700.00,
  '60% OFF',
  'Like New',
  6,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=Made+Easy+Maths'],
  NULL,
  'Made Easy Publications',
  '2023 Edition',
  'English',
  'Complete engineering mathematics book for GATE covering Linear Algebra, Calculus, Probability, Numerical Methods, and Complex Variables with 3000+ solved GATE questions.',
  true,
  true
),
(
  'GATE CSE Previous Year Solved Papers (30 Years)',
  'Made Easy',
  'Academic',
  'GATE/CS',
  320.00,
  800.00,
  '60% OFF',
  'Good',
  4,
  ARRAY['https://placehold.co/300x400/1a1a2e/e94560?text=GATE+CSE+Papers'],
  NULL,
  'Made Easy Publications',
  '2024 Edition',
  'English',
  '30 years of GATE Computer Science solved papers organized chapter-wise. Includes detailed solutions and topic-wise analysis. Must-have for GATE CSE preparation.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- ACADEMIC — School (CBSE/ISC)
-- ═══════════════════════════════════════════════════════════════════
(
  'RD Sharma Mathematics Class 12 (Vol 1 & 2)',
  'RD Sharma',
  'Academic',
  'Mathematics/School',
  300.00,
  750.00,
  '60% OFF',
  'Good',
  7,
  ARRAY['https://placehold.co/300x400/1a1a2e/3a0ca3?text=RD+Sharma+12th'],
  NULL,
  'Dhanpat Rai Publications',
  'Latest Edition',
  'English',
  'Two-volume set of RD Sharma Mathematics for Class 12 CBSE. Covers relations, functions, calculus, vectors, probability, and linear programming with detailed solutions.',
  true,
  false
),
(
  'NCERT Chemistry Class 11 & 12 Set',
  'NCERT',
  'Academic',
  'Chemistry/School',
  140.00,
  380.00,
  '60% OFF',
  'Good',
  10,
  ARRAY['https://placehold.co/300x400/1a1a2e/4361ee?text=NCERT+Chem+Set'],
  NULL,
  'NCERT',
  'Latest Edition',
  'English',
  'Complete set of NCERT Chemistry textbooks for Class 11 and 12. Foundation for JEE, NEET, and board exams covering Physical, Organic, and Inorganic Chemistry.',
  true,
  false
),
(
  'All in One - English Core Class 12',
  'Arihant Experts',
  'Academic',
  'English/School',
  160.00,
  425.00,
  '60% OFF',
  'Fair',
  5,
  ARRAY['https://placehold.co/300x400/1a1a2e/f59e0b?text=All+in+One+Eng'],
  NULL,
  'Arihant Publications',
  '2024 Edition',
  'English',
  'Complete English Core study guide for Class 12 CBSE board exams. Includes chapter summaries, grammar, writing skills, and previous year solved papers.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- SELF-HELP
-- ═══════════════════════════════════════════════════════════════════
(
  'Deep Work by Cal Newport',
  'Cal Newport',
  'Self-Help',
  NULL,
  160.00,
  450.00,
  '60% OFF',
  'Like New',
  8,
  ARRAY['https://placehold.co/300x400/0f3460/f59e0b?text=Deep+Work'],
  '978-1455586660',
  'Grand Central Publishing',
  '1st Edition',
  'English',
  'Rules for focused success in a distracted world. Learn how to cultivate deep focus, eliminate distractions, and master the art of concentrated work for academic and professional excellence.',
  true,
  true
),
(
  'Ikigai — The Japanese Secret to a Long and Happy Life',
  'Héctor García & Francesc Miralles',
  'Self-Help',
  NULL,
  130.00,
  350.00,
  '60% OFF',
  'Good',
  6,
  ARRAY['https://placehold.co/300x400/0f3460/06d6a0?text=Ikigai'],
  '978-1786330895',
  'Penguin Books',
  '1st Edition',
  'English',
  'Discover the Japanese concept of Ikigai — finding your reason for being. A blend of neuroscience, psychology, and wisdom from Okinawa, the island with the longest-living people.',
  true,
  false
),
(
  'The Power of Your Subconscious Mind',
  'Joseph Murphy',
  'Self-Help',
  NULL,
  90.00,
  250.00,
  '60% OFF',
  'Fair',
  9,
  ARRAY['https://placehold.co/300x400/0f3460/e94560?text=Subconscious+Mind'],
  '978-8188452530',
  'Jaico Publishing House',
  'Revised Edition',
  'English',
  'Classic self-help book teaching how to harness the power of your subconscious mind for success, healing, and happiness. Over 1 million copies sold worldwide.',
  true,
  false
),
(
  'Rich Dad Poor Dad',
  'Robert Kiyosaki',
  'Self-Help',
  NULL,
  110.00,
  299.00,
  '60% OFF',
  'Good',
  12,
  ARRAY['https://placehold.co/300x400/0f3460/f59e0b?text=Rich+Dad+Poor+Dad'],
  '978-9386451045',
  'Westland Publications',
  '2017 Edition',
  'English',
  'The #1 personal finance book of all time. Learn what the rich teach their kids about money that the poor and middle class do not. Essential financial literacy for students.',
  true,
  true
),
(
  'Think and Grow Rich',
  'Napoleon Hill',
  'Self-Help',
  NULL,
  85.00,
  230.00,
  '60% OFF',
  'Fair',
  7,
  ARRAY['https://placehold.co/300x400/0f3460/3a0ca3?text=Think+Grow+Rich'],
  '978-9387669460',
  'Fingerprint Publishing',
  'Deluxe Edition',
  'English',
  'The original self-help classic based on 20 years of research on America''s most successful people. Learn the 13 principles of wealth creation and personal achievement.',
  true,
  false
),
(
  'How to Win Friends and Influence People',
  'Dale Carnegie',
  'Self-Help',
  NULL,
  100.00,
  280.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/0f3460/4361ee?text=Win+Friends'],
  '978-8187981424',
  'Bloomsbury Publishing',
  'Revised Edition',
  'English',
  'Timeless guide to human relations. Learn fundamental techniques for handling people, winning people to your way of thinking, and becoming a leader. Over 30 million copies sold.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- FICTION
-- ═══════════════════════════════════════════════════════════════════
(
  'Sapiens — A Brief History of Humankind',
  'Yuval Noah Harari',
  'Fiction',
  'Non-Fiction',
  200.00,
  550.00,
  '60% OFF',
  'Like New',
  6,
  ARRAY['https://placehold.co/300x400/1b1b2f/f59e0b?text=Sapiens'],
  '978-0062316097',
  'Harper Perennial',
  '1st Edition',
  'English',
  'A groundbreaking narrative of humanity''s creation and evolution. From the Stone Age to the Silicon Age, Harari explores how biology and history have defined us. Must-read for curious minds.',
  true,
  true
),
(
  'The Alchemist',
  'Paulo Coelho',
  'Fiction',
  'Fiction/Philosophy',
  100.00,
  299.00,
  '60% OFF',
  'Good',
  10,
  ARRAY['https://placehold.co/300x400/1b1b2f/e94560?text=Alchemist'],
  '978-0062315007',
  'HarperOne',
  '25th Anniversary Edition',
  'English',
  'A mystical story about Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. A fable about following your dreams and listening to your heart.',
  true,
  true
),
(
  '3 Mistakes of My Life',
  'Chetan Bhagat',
  'Fiction',
  'Indian Fiction',
  80.00,
  199.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/1b1b2f/4361ee?text=3+Mistakes'],
  '978-8129115308',
  'Rupa Publications',
  '1st Edition',
  'English',
  'Story of three friends in Ahmedabad who make mistakes — in business, with love, and with cricket. A relatable tale about friendship, ambition, and the choices that define us.',
  true,
  false
),
(
  'The Immortals of Meluha (Shiva Trilogy #1)',
  'Amish Tripathi',
  'Fiction',
  'Indian Fiction/Mythology',
  150.00,
  399.00,
  '60% OFF',
  'Like New',
  5,
  ARRAY['https://placehold.co/300x400/1b1b2f/f59e0b?text=Immortals+Meluha'],
  '978-9382618330',
  'Westland Publications',
  '2015 Edition',
  'English',
  'First book of the Shiva Trilogy. A breathtaking adventure of a simple man whose unexpected destiny transforms him into a living God. Bestselling Indian mythology fiction.',
  true,
  false
),
(
  'Harry Potter Complete Set (7 Books Box)',
  'J.K. Rowling',
  'Fiction',
  'Fantasy',
  1200.00,
  3500.00,
  '60% OFF',
  'Like New',
  2,
  ARRAY['https://placehold.co/300x400/1b1b2f/3a0ca3?text=Harry+Potter+Set'],
  '978-0747595823',
  'Bloomsbury Publishing',
  '2014 Edition',
  'English',
  'Complete set of all 7 Harry Potter books in a special box set. Follow Harry''s magical journey from the Sorcerer''s Stone to the Deathly Hallows. The complete wizarding world experience.',
  true,
  true
),
(
  '5 Point Someone',
  'Chetan Bhagat',
  'Fiction',
  'Indian Fiction',
  75.00,
  195.00,
  '60% OFF',
  'Fair',
  7,
  ARRAY['https://placehold.co/300x400/1b1b2f/06d6a0?text=5+Point+Someone'],
  '978-8129104593',
  'Rupa Publications',
  '2004 Edition',
  'English',
  'The story of three IIT students who mess up their grades and their lives. A witty, honest look at the pressure cooker environment of India''s top engineering college.',
  true,
  false
),
(
  'To Kill a Mockingbird',
  'Harper Lee',
  'Fiction',
  'Classic Fiction',
  120.00,
  350.00,
  '60% OFF',
  'Good',
  4,
  ARRAY['https://placehold.co/300x400/1b1b2f/e94560?text=To+Kill+Mockingbird'],
  '978-0061120084',
  'Harper Perennial',
  '50th Anniversary Edition',
  'English',
  'Pulitzer Prize-winning classic about racial injustice in 1930s Alabama. Through the eyes of Scout Finch, witness her father Atticus defend a Black man wrongly accused of a crime.',
  true,
  false
),

-- ═══════════════════════════════════════════════════════════════════
-- OTHERS — Competitive Exams, Programming, etc.
-- ═══════════════════════════════════════════════════════════════════
(
  'Let Us C by Yashavant Kanetkar',
  'Yashavant Kanetkar',
  'Others',
  'Programming',
  130.00,
  360.00,
  '60% OFF',
  'Good',
  9,
  ARRAY['https://placehold.co/300x400/0d1b2a/f59e0b?text=Let+Us+C'],
  '978-8183335427',
  'BPB Publications',
  '16th Edition',
  'English',
  'India''s most popular C programming book. Step-by-step approach to learning C with 200+ programs and exercises. Perfect for engineering students and beginners in programming.',
  true,
  true
),
(
  'Cracking the Coding Interview',
  'Gayle Laakmann McDowell',
  'Others',
  'Programming',
  350.00,
  850.00,
  '60% OFF',
  'Like New',
  3,
  ARRAY['https://placehold.co/300x400/0d1b2a/4361ee?text=Coding+Interview'],
  '978-0984782857',
  'CareerCup',
  '6th Edition',
  'English',
  'The definitive guide to coding interviews. Contains 189 programming questions and solutions from top tech companies. Must-read for software engineering placements.',
  true,
  true
),
(
  'A Modern Approach to Verbal & Non-Verbal Reasoning',
  'R.S. Aggarwal',
  'Others',
  'Competitive Exams',
  250.00,
  650.00,
  '60% OFF',
  'Good',
  6,
  ARRAY['https://placehold.co/300x400/0d1b2a/e94560?text=Verbal+NonVerbal'],
  NULL,
  'S. Chand & Co.',
  'Latest Edition',
  'English',
  'Comprehensive reasoning book covering verbal, non-verbal, and analytical reasoning. Used for banking, SSC, railway, and all government competitive exam preparation.',
  true,
  false
),
(
  'Quantitative Aptitude for Competitive Exams',
  'R.S. Aggarwal',
  'Others',
  'Competitive Exams',
  200.00,
  525.00,
  '60% OFF',
  'Good',
  8,
  ARRAY['https://placehold.co/300x400/0d1b2a/3a0ca3?text=Quant+Aptitude'],
  NULL,
  'S. Chand & Co.',
  'Latest Edition',
  'English',
  'The go-to book for quantitative aptitude in Indian competitive exams. Covers arithmetic, algebra, geometry, data interpretation, and data sufficiency with 5500+ questions.',
  true,
  false
),
(
  'Manorama Year Book 2024',
  'Malayala Manorama',
  'Others',
  'General Knowledge',
  150.00,
  399.00,
  '60% OFF',
  'Like New',
  4,
  ARRAY['https://placehold.co/300x400/0d1b2a/06d6a0?text=Manorama+2024'],
  NULL,
  'Malayala Manorama',
  '2024 Edition',
  'English',
  'India''s best-selling general knowledge yearbook. Covers current affairs, Indian history, geography, science, sports, awards, and government schemes — essential for all competitive exams.',
  true,
  false
),
(
  'Introduction to Algorithms (CLRS)',
  'Cormen, Leiserson, Rivest, Stein',
  'Others',
  'Programming/CS',
  550.00,
  1350.00,
  '60% OFF',
  'Good',
  2,
  ARRAY['https://placehold.co/300x400/0d1b2a/f59e0b?text=CLRS+Algorithms'],
  '978-0262033848',
  'MIT Press',
  '4th Edition',
  'English',
  'The gold standard textbook on algorithms. Comprehensive coverage of algorithms and data structures with mathematical rigor. Used in IITs and top universities worldwide.',
  true,
  true
),
(
  'India 2024 (Ministry of Info & Broadcasting)',
  'Publication Division',
  'Others',
  'UPSC/GK',
  180.00,
  475.00,
  '60% OFF',
  'Good',
  5,
  ARRAY['https://placehold.co/300x400/0d1b2a/e94560?text=India+2024'],
  NULL,
  'Publication Division, Govt of India',
  '2024 Edition',
  'English',
  'Official reference book on India published by the Government of India. Covers Indian economy, polity, science & technology, culture, and current affairs for UPSC and state PCS exams.',
  true,
  false
);
